---=========================================================== BANKING PROJECT ==============================================
CREATE TABLE customers (
    customer_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR2(50),
    mobile_no     VARCHAR2(15),
    city          VARCHAR2(30),
    PRIMARY KEY (customer_id)
);

CREATE TABLE accounts (
    account_no    NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000000 INCREMENT BY 1),
    customer_id   NUMBER,
    balance       NUMBER(12,2),
    PRIMARY KEY (account_no),
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);
select * from accounts;
alter table transactions modify account_no number(11);
CREATE TABLE transactions (
    txn_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    account_no    NUMBER,
    txn_type      VARCHAR2(10),   -- CREDIT / DEBIT
    amount        NUMBER(12,2),
    txn_date      DATE DEFAULT SYSDATE,
    PRIMARY KEY (txn_id)
);
desc transactions;
DROP PACKAGE bank_pkg;

set serveroutput on;
Create or replace package bank_pkg 
as
--Create customer
procedure create_customer(c_name varchar2, c_mobno varchar2,c_city varchar2);
procedure add_account(a_custid number, a_balance number);
procedure deposit(d_account_no number, d_amount number);
procedure withdraw(w_account_no number, w_amount number);
function balance(b_custid number) return number;
procedure mini_statement(m_account_no number);
End bank_pkg;
/

Create or replace package body bank_pkg
as

procedure create_customer(c_name varchar2, c_mobno varchar2, c_city varchar2)
as
v_name varchar(20);
Begin
    insert into customers(name, mobile_no, city) values (c_name, c_mobno, c_city);
    select name into v_name from customers where name=c_name;
    dbms_output.put_line('New Customer : '||v_name||' Created!!');
    commit;
End;

procedure add_account(a_custid number, a_balance number)
as
v_custid varchar(20);
Begin
    insert into accounts(customer_id, balance) values(a_custid, a_balance);
    select customer_id into v_custid from accounts where customer_id=a_custid;
    dbms_output.put_line('New Account with customer id : '||v_custid||' Created!!');
    commit;
End;

procedure deposit(d_account_no number, d_amount number)
as
Begin
    update accounts set balance = balance + d_amount where account_no=d_account_no;
    insert into transactions(account_no, txn_type, amount) values(d_account_no,'CREDIT', d_amount);
    commit;
    dbms_output.put_line('Amount of rs : '||d_amount||' Credited Successfully!!!');
End;

procedure withdraw(w_account_no number, w_amount number)
as
v_balance NUMBER(12,2);
Begin
    select balance into v_balance from accounts where account_no=w_account_no;
    if (w_amount>v_balance)
    then
    RAISE_APPLICATION_ERROR(-20001, 'Insufficient balance');
    end if;
    
    update accounts set balance = balance - w_amount where account_no=w_account_no;
    insert into transactions(account_no, txn_type, amount) values(w_account_no, 'DEBIT', w_amount);
    commit;
    dbms_output.put_line('Amount of rs : '||w_amount||' Debited Successfully!!!');
End;

function balance(b_custid number) return number
as
b_balance NUMBER(12,2);
Begin
    select balance into b_balance from accounts where customer_id=b_custid;
    return b_balance;
End;

procedure mini_statement(m_account_no number)
as
type ref_cursor_type is REF cursor;
c1 ref_cursor_type; 
m_txn_id number;
m_txn_type VARCHAR2(10);
m_amount NUMBER(12,2);
m_txn_date date;
Begin
    open c1 for select txn_id, txn_type, amount, txn_date from transactions where account_no=m_account_no;
    loop
    fetch c1 into m_txn_id, m_txn_type, m_amount, m_txn_date;
    exit when c1%notfound;
    dbms_output.put_line(m_txn_id || ' | ' || m_txn_type || ' | ' || m_amount || ' | ' || m_txn_date);
    end loop;
    close c1;
End;
End bank_pkg;
/


--TESTING THE PROJECT

--⭐ Create customer
exec bank_pkg.create_customer('Suyog', '9082051918', 'Mumbai');
exec bank_pkg.create_customer('Smita', '9082051919', 'Mumbai');
select * from customers;

--⭐ Open account
EXEC bank_pkg.add_account(1,1000);
EXEC bank_pkg.add_account(2,1000);
select * from accounts;

--⭐ Deposit
EXEC bank_pkg.deposit(1000000000, 50000);
EXEC bank_pkg.deposit(1000000001, 500);
select * from accounts;

--⭐ Withdraw
EXEC bank_pkg.withdraw(1000000000, 500);
EXEC bank_pkg.withdraw(1000000001, 500);
select * from accounts;

--⭐ Check balance
SELECT bank_pkg.balance(2) AS Suyogsbalance FROM dual;
SELECT bank_pkg.balance(2) AS Smitasbalance FROM dual;

--⭐ Mini Statement
EXEC bank_pkg.mini_statement(1000000000);
EXEC bank_pkg.mini_statement(1000000001);
